#define QingApi                     ixSoAhtl
#define SdkCallbackBlock            YERmOsSB
#define initWithGameKey             ZLjDQOTp
#define qingShowLoginWithBlock      PlbkjkfF
#define qingLogout                  BYcAUDkR
#define qingIsPaymentUsable         jasPaoFq
#define qingRequestOrderWithParams  BLtXOBJy
#define QingUserInfo                RPPoYudz
#define QingOrderParams             zxYyYPQy
#define QingOrderResult             wqDojkja
#define QingUserBlock               XnrsFRwf
#define QingOrderResultBlock        oGmoONyN
#define qing_user_id                OsQRaDwg
#define qing_user_token             EPsSwzSd
#define qing_product_name           spfpHccW
#define qing_product_price          vjTPETZU
#define qing_cp_order_id            wFPAjYsV
#define qing_is_sandbox             lnSNRIug
#define qing_extends_param1         CsDSswwH
#define qing_extends_param2         LWAQaTox
#define qing_order_id               VGESeANG
#define qing_state                  IlwPEYIP
#define qing_message                WdqNHdYe
