#define QingApi                     FkeHTkhC
#define SdkCallbackBlock            natMVGiQ
#define initWithGameKey             CiIvAtxc
#define qingShowLoginWithBlock      NjLWGNqy
#define qingLogout                  wtiMBUfa
#define qingIsPaymentUsable         TkXMBRYl
#define qingRequestOrderWithParams  dMFZcsrj
#define QingUserInfo                GbeOEGiw
#define QingOrderParams             KszpzrFR
#define QingOrderResult             zkleTzsT
#define QingUserBlock               qkYvfMFn
#define QingOrderResultBlock        gXIdgWVW
#define qing_user_id                IJQPwoGc
#define qing_user_token             pOXPFiCs
#define qing_product_name           kvCHEIxs
#define qing_product_price          zunefvin
#define qing_cp_order_id            NfzPgink
#define qing_is_sandbox             jVMYoFVz
#define qing_extends_param1         epYpFINa
#define qing_extends_param2         qhvNmmDs
#define qing_order_id               CXdsPLkX
#define qing_state                  ukEFIEXW
#define qing_message                oTcfSpsB
