#define QingApi                     KWgcnaVt
#define SdkCallbackBlock            tYDuLJBK
#define initWithGameKey             cHKaqMGL
#define qingShowLoginWithBlock      FIMimgKJ
#define qingLogout                  iimNjmYu
#define qingIsPaymentUsable         AhxlwBxp
#define qingRequestOrderWithParams  jjwyvKZO
#define QingUserInfo                KrzSWiwg
#define QingOrderParams             xTYWZTWO
#define QingOrderResult             pPrBYRwm
#define QingUserBlock               OqhXZDoo
#define QingOrderResultBlock        gmILEIzs
#define qing_user_id                ZoBwcLtt
#define qing_user_token             jsGEPxhM
#define qing_product_name           vtemoLeW
#define qing_product_price          HWHvhJER
#define qing_cp_order_id            tauHElaO
#define qing_is_sandbox             hhfjYsaX
#define qing_extends_param1         KfBVKdNe
#define qing_extends_param2         LdnsTYGy
#define qing_order_id               htPoCsVK
#define qing_state                  ntslstcP
#define qing_message                VAXZrKXW
